# Site settings
# 블로그이름
title: "Selen"
#블로그 설명
description: "개인 블로그 "

  #현재 테마는 다른 주소로 되어있을 수도 있어 바로 적용을 확인하면 에러가 발생할 수도 있다.
  # 따라서 baseurl은 ““으로 url은 “[내블로그주소]“로 변경해주어야 한다.
baseurl: ""
#블로그 메인 사이트 
url: "https://imselen.github.io/"

# Banner Section
hero: 28.jpg
hero-title: Line
hero-description: Line

# Author - Creator
author-name: Selen
author-image: 15.jpg
about-author: my name is selen. This is my first git blog!
author-email: volu7070@gmail.com


# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  Natali_Braxton:
    author-name: Selen
    author-image: 11.jpg # gulpfile.js에서 경로 확인
    about-author: My name is selen. This is my first git blog!
    author-email: volu7070@gmail.com


# Contact Form Settings
contact-subtitle: "연락이 필요할 때 메일 주세요"


# Google Analytics
# 구글 애널리틱스 측정아이디 설정
google-analytics: G-MVD4XJGH30 # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Comment Section (Disqus)
# Add your shortname for Disqus Comment.
disqus-identifier: https-imselen-github-io-1 #disqus홈페이지에서 사이트 등록 시 생성
comments : true # 코멘트 허락 + 댓글 등록 확인 완료

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3 #원래 숫자 : 9
paginate_path: "/page/:num"

# Pages path
# 페이지 경로 고정지정
defaults:
   # posts 쪽과 pages 쪽으로 나눠짐
   # _pages
  - scope:
      path: '_pages'
    values:
      comments : true
      share : ture
      permalink: /:basename:output_ext

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - _pages

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - vendor
